kernel: gaussian
kernel_size: 64
intensity: 4.0
tilt_dir: /media/harry/tomo/turbulence/tilt_256x256

conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples

measurement:
  operator:
    name: turbulence
  
  noise: 
    name: gaussian
    sigma: 0.02
